### ISSUE TITLE
The reverse function has a problem

### ISSUE THREAD

**Issue by leandroimail** [gdkrmr/DRR#2]
I have received the follow error:

> Error in outdat %*% t(pca$rotation) : non-conformable arguments

So, I checked the code of DRR and saw what you use the following code: 

`pca$rotation <- diag(1, ncol(X), ncol(X))`

In this case is being disregarded the _ndim_ variable because _ndim_ can be different from _ncol(X)_, so, the _pca$rotation_ return wrong and when It is used the function _inverse_  throw the error.

**Comment by gdkrmr** [comment]
Good catch, thank you! Can you make a PR?

**Comment by gdkrmr** [comment]
Could you give a minimal working example, I don't see it, `outdat` should always have `ncol(X)` columns.

**Comment by leandroimail** [comment]
> Could you give a minimal working example, I don't see it, `outdat` should always have `ncol(X)` columns.

Ok.

I  will put my code here. Context is: I have a dataset with 42747 columns and 500 rows and I want to reduce to 8 components. 

```
num_dimentions  <- 8
path_file <- "Path of your dataset"

df <- read.csv(file=path_file, header=TRUE, sep=",")
df_drr <- drr(df, ndim = num_dimentions)

#### Here I recive the ERROR: Error in outdat %*% t(pca$rotation) : non-conformable arguments ##############
df_drr$inverse(df_drr$fitted.data)

###### It work in this way ##############
df_drr_rotation <- df_drr$pca.rotation[,1:num_dimentions]
df_drr_center <- df_drr$pca.means
df_drr_result <- df_drr$fitted.data
df_drr_rev <- t(t(df_drr_result %*% t(df_drr_rotation)) + df_drr_center)

```

If you to check the _stats::prcomp_ always return 500 components ("columns"). So, if you don't restrain pca.rotation by _ndin_ you will receive the error. 

You can see this in this post of StackExchange: 
[How to reverse PCA and reconstruct original variables from several principal components?](https://stats.stackexchange.com/questions/229092/how-to-reverse-pca-and-reconstruct-original-variables-from-several-principal-com?answertab=votes#tab-top)

Observe in the R code that he restrains the _rotation_ by _nComp_.

**Comment by gdkrmr** [comment]
You have more variables than observations, I never considered this case, I really doubt that DRR can or should handle this. Of course, you will only get up to 500 positive eigenvalues for the PCA preprocessing. I should probably check for that and ensure that `nrow(X) > ncol(X)`.

DRR is pretty slow and you wouldn't want to crossvalidate 500 KRRs. I guess your best bet is to do a manual pca first and get it down to 50 dimensions or so and then use `drr(..., pca = FALSE)`.

EDIT: I see that you only want to fit 8 dimensions...

**Comment by gdkrmr** [comment]
There should be a branche `widex` now, it would be cool if you could test it out and report back!

**Comment by gdkrmr** [comment]
Thanks for reporting this, the new version is on CRAN and should soon be available as binary packages.
